name: Fix Command

on:
  issue_comment:
    types: [created]

jobs:
  fix:
    runs-on: ubuntu-latest
    if: >
      github.event.issue.pull_request &&
      (startsWith(github.event.comment.body, '/fix ') ||
       github.event.comment.body == '/fix')
    steps:
      - run: echo "Fix command works!"
